= CircleCI Server システム管理者向けのメトリクス概要
:toc: left
:toc-title: 目次
:circleci-doc: https://circleci.com/docs/2.0/

メトリクスは、サーバー上にインストールした CircleCI のモニタリングと分析に役立ちます。このドキュメントでは、CircleCI Server でのメトリクスと使用方法の概要を紹介します。

== CircleCI Server でのメトリクス
メトリクスとは、運行中のマシンから測定と収集できるデータです。CPU やメモリの使用率といった基本情報から、ビルドの実行とエラーの数など⾼度なデータまであります。

* システムの異常を検知し、アラート通知を設定できます。
* インフラストラクチャにある潜在的な問題を検出できます。
* コンピューティングリソースの使用率に基づきスケールし、コストを最適化できます。

CircleCI Server では、
https://www.influxdata.com/time-series-platform/telegraf[Telegraf] を使用してメトリクスを収集します。Telegraf は、
{circleci-doc}overview/?section=server-administration#architecture[Services マシン]から収集したメトリクスを DataDog や AWS CloudWatch などのデータモニタリングプラットフォームに送信できます。詳細については、
{circleci-doc}monitoring/#how-metrics-work-in-circleci-server[CircleCI Server でのメトリクスの仕組み]を参照してください。

== メトリクスの使用を開始する
以下のページを参照することをおすすめします。

* {circleci-doc}monitoring/#standard-metrics-configuration[標準のメトリクス設定]：メトリクスの設定ファイルを確認します。

WARNING: 標準設定以外をお使いの場合、
{circleci-doc}monitoring/#custom-metrics[カスタムメトリクス]ページを参照してください。あらかじめ標準設定を無効にする必要があります。

* {circleci-doc}monitoring/#system-monitoring-metrics[モニタリングできるメトリクスの種類]

* {circleci-doc}monitoring/#supported-platforms[対応プラットフォーム (AWS CloudWatch と DataDog)]