version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout
      - run:
          name: Upload as artifact
          command: 
           cp /Techdoc/metrics.adoc > /artifact-1

      - store_artifacts:
          path: /artifact-1
