version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout
      - run:
          name: Upload as artifact
          command: 
           ./Techdoc/metrics.adoc

      - store_artifacts:
          path: /artifact-1
