version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Upload as artifact
          command: 
           /Techdoc/metrics.adoc > /tmp/artifact-1

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
