version: 2.1

jobs:
  build:
    docker:
      - image: python:3.6.3-jessie

    working_directory: /circleci/TechDoc
    steps:
      - run:
          name: Creating Artifact
          command: |
            echo "This is a sample artifact" > /circleci/TechDoc

      - store_artifacts:
          path: /techdoc/artifact